### ISSUE TITLE
Not on CPAN.

### ISSUE THREAD

**Issue by bobtfish** [cooldaemon/RabbitFoot#1]
Hiya.

Can you release this to CPAN, or at least tag a version in git so that I can build a company internal package for a specific numbered version?

Thanks in advance.

**Comment by cooldaemon** [comment]
Thank you for your inquiry about the RabbitFoot.
After excluding the Moose dependence, I add a tag for release.
Maybe, I can release it to CPAN next month.

**Comment by bobtfish** [comment]
I don't in any way have an issue with the dependency on Moose.

In fact, I was quite sad that Moose was removed :( Either way - does this have to block a release?

FYI I have an initial application that I'm using quite ready to being CPAN ready:
http://github.com/bobtfish/App-RabbitTail

**Comment by cooldaemon** [comment]
I release the RabbitFoot to CPAN.
http://search.cpan.org/~ikuta/RabbitFoot/

I love Moose. I am using Moose well on business.
But it is loading slows.

> http://github.com/bobtfish/App-RabbitTail
> cool!!

**Comment by bobtfish** [comment]
On cpan now, thanks :)

**Comment by cooldaemon** [comment]
I fixed module name.
Please check a follow link.
http://search.cpan.org/~ikuta/Net-RabbitFoot/
