### ISSUE TITLE
server dieing does not call back to my code.

### ISSUE THREAD

**Issue by bobtfish** [cooldaemon/RabbitFoot#2]
Hiya.

If you're connected to a RabbitMQ server, and the server unexpectedly goes away, then the on_failure callback to ->connect in AnyEvent::RabbitMQ is called.

This is passed by _do in Net::RabbitFoot and is a coro rouse_cb. However that is only used for checking the connection works, and so later when it is called back to, it has no effect.

I would have expected one of the on_close, or on_failure callbacks I'd passed to the connect method to be called instead, as I'd like to be able to handle reconnecting automatically if the connection to the server is interrupted in long running processes.

Cheers
t0m

**Comment by cooldaemon** [comment]
Thank you for your bug report.
I'm going to check a callback function for disconnect.

**Comment by cooldaemon** [comment]
Maybe I would add on_close function to AnyEvent::RabbitMQ and Net::RabbitFoot.

**Comment by cooldaemon** [comment]
I thought that there was a problem in my patches.
http://github.com/cooldaemon/RabbitFoot/commit/e5e912e22f333e207cda38ba68872c80883f26ec

However, when it was tested, it ran well.
Could you check the following test code?
http://gist.github.com/330391

**Comment by bobtfish** [comment]
Fixed, thank!
